# Generated by Django 3.1.5 on 2021-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('donator', 'donator')], max_length=50, null=True),
        ),
    ]
